name: Build

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 3 * * 0'

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU (for multi platform build)
        uses: docker/setup-qemu-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest
          target: prod
          platforms: linux/amd64,linux/arm64
          push: true
